version: '3'
services:
    php:
        build: docker/php
        working_dir: /usr/local/src/php-7.4.2
        volumes:
            - ./src:/var/www/src
        links:
          - mysql
    php-7.4:
        image: php:7.4-fpm
        volumes:
            - ./src:/var/www/src
    nginx:
        build: docker/nginx
        ports:
            - 8080:80
        volumes:
            - ./src:/var/www/src
            - ./log/nginx:/var/log/nginx/
        links:
            - php
    mysql:
        build:
            context: docker/mysql/
        ports:
            - 33061:3306
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
            MYSQL_USER: 'test'
            MYSQL_PASSWORD: 'test'
            MYSQL_DATABASE: 'test'